package MyVerein::Model::MyVereinDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MyVerein::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:myverein',
        user => 'mvdbuser',
        password => 'mvdbpassword',
    }
);

=head1 NAME

MyVerein::Model::MyVereinDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MyVerein>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MyVerein::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR



=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
